/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppChatRouteImport } from './routes/_app/chat'
import { Route as AppAgentsAgentIdRouteImport } from './routes/_app/agents.$agentId'
import { Route as AppManageAgentsRouteImport } from './routes/_app/manage.agents'
import { Route as AppManageSkillsRouteImport } from './routes/_app/manage.skills'
import { Route as AppManageToolkitsRouteImport } from './routes/_app/manage.toolkits'
import { Route as AppManageWorkflowsRouteImport } from './routes/_app/manage.workflows'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentsAgentIdRoute = AppAgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => AppRoute,
} as any)
const AppManageAgentsRoute = AppManageAgentsRouteImport.update({
  id: '/manage/agents',
  path: '/manage/agents',
  getParentRoute: () => AppRoute,
} as any)
const AppManageSkillsRoute = AppManageSkillsRouteImport.update({
  id: '/manage/skills',
  path: '/manage/skills',
  getParentRoute: () => AppRoute,
} as any)
const AppManageToolkitsRoute = AppManageToolkitsRouteImport.update({
  id: '/manage/toolkits',
  path: '/manage/toolkits',
  getParentRoute: () => AppRoute,
} as any)
const AppManageWorkflowsRoute = AppManageWorkflowsRouteImport.update({
  id: '/manage/workflows',
  path: '/manage/workflows',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/chat': typeof AppChatRoute
  '/agents/$agentId': typeof AppAgentsAgentIdRoute
  '/manage/agents': typeof AppManageAgentsRoute
  '/manage/skills': typeof AppManageSkillsRoute
  '/manage/toolkits': typeof AppManageToolkitsRoute
  '/manage/workflows': typeof AppManageWorkflowsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/chat': typeof AppChatRoute
  '/agents/$agentId': typeof AppAgentsAgentIdRoute
  '/manage/agents': typeof AppManageAgentsRoute
  '/manage/skills': typeof AppManageSkillsRoute
  '/manage/toolkits': typeof AppManageToolkitsRoute
  '/manage/workflows': typeof AppManageWorkflowsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/agents/$agentId': typeof AppAgentsAgentIdRoute
  '/_app/manage/agents': typeof AppManageAgentsRoute
  '/_app/manage/skills': typeof AppManageSkillsRoute
  '/_app/manage/toolkits': typeof AppManageToolkitsRoute
  '/_app/manage/workflows': typeof AppManageWorkflowsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/chat'
    | '/agents/$agentId'
    | '/manage/agents'
    | '/manage/skills'
    | '/manage/toolkits'
    | '/manage/workflows'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/chat'
    | '/agents/$agentId'
    | '/manage/agents'
    | '/manage/skills'
    | '/manage/toolkits'
    | '/manage/workflows'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/chat'
    | '/_app/agents/$agentId'
    | '/_app/manage/agents'
    | '/_app/manage/skills'
    | '/_app/manage/toolkits'
    | '/_app/manage/workflows'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agents/$agentId': {
      id: '/_app/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AppAgentsAgentIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/manage/agents': {
      id: '/_app/manage/agents'
      path: '/manage/agents'
      fullPath: '/manage/agents'
      preLoaderRoute: typeof AppManageAgentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/manage/skills': {
      id: '/_app/manage/skills'
      path: '/manage/skills'
      fullPath: '/manage/skills'
      preLoaderRoute: typeof AppManageSkillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/manage/toolkits': {
      id: '/_app/manage/toolkits'
      path: '/manage/toolkits'
      fullPath: '/manage/toolkits'
      preLoaderRoute: typeof AppManageToolkitsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/manage/workflows': {
      id: '/_app/manage/workflows'
      path: '/manage/workflows'
      fullPath: '/manage/workflows'
      preLoaderRoute: typeof AppManageWorkflowsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppChatRoute: typeof AppChatRoute
  AppAgentsAgentIdRoute: typeof AppAgentsAgentIdRoute
  AppManageAgentsRoute: typeof AppManageAgentsRoute
  AppManageSkillsRoute: typeof AppManageSkillsRoute
  AppManageToolkitsRoute: typeof AppManageToolkitsRoute
  AppManageWorkflowsRoute: typeof AppManageWorkflowsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChatRoute: AppChatRoute,
  AppAgentsAgentIdRoute: AppAgentsAgentIdRoute,
  AppManageAgentsRoute: AppManageAgentsRoute,
  AppManageSkillsRoute: AppManageSkillsRoute,
  AppManageToolkitsRoute: AppManageToolkitsRoute,
  AppManageWorkflowsRoute: AppManageWorkflowsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
